/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfilePasswordRouteImport } from './routes/profile/password'
import { Route as ProfileInvitesRouteImport } from './routes/profile/invites'
import { Route as ApiScopedRagStreamRouteImport } from './routes/api/scoped-rag-stream'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat-events'
import { Route as ApiArtifactsRouteImport } from './routes/api/artifacts'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfilePasswordRoute = ProfilePasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileInvitesRoute = ProfileInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => ProfileRoute,
} as any)
const ApiScopedRagStreamRoute = ApiScopedRagStreamRouteImport.update({
  id: '/api/scoped-rag-stream',
  path: '/api/scoped-rag-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/api/chat-events',
  path: '/api/chat-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/scoped-rag-stream': typeof ApiScopedRagStreamRoute
  '/profile/invites': typeof ProfileInvitesRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/docs': typeof DocsRoute
  '/sign-in': typeof SignInRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/scoped-rag-stream': typeof ApiScopedRagStreamRoute
  '/profile/invites': typeof ProfileInvitesRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/scoped-rag-stream': typeof ApiScopedRagStreamRoute
  '/profile/invites': typeof ProfileInvitesRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/docs'
    | '/profile'
    | '/sign-in'
    | '/admin/users'
    | '/api/artifacts'
    | '/api/chat-events'
    | '/api/events'
    | '/api/scoped-rag-stream'
    | '/profile/invites'
    | '/profile/password'
    | '/admin/'
    | '/profile/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/docs'
    | '/sign-in'
    | '/admin/users'
    | '/api/artifacts'
    | '/api/chat-events'
    | '/api/events'
    | '/api/scoped-rag-stream'
    | '/profile/invites'
    | '/profile/password'
    | '/admin'
    | '/profile'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/docs'
    | '/profile'
    | '/sign-in'
    | '/admin/users'
    | '/api/artifacts'
    | '/api/chat-events'
    | '/api/events'
    | '/api/scoped-rag-stream'
    | '/profile/invites'
    | '/profile/password'
    | '/admin/'
    | '/profile/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiArtifactsRoute: typeof ApiArtifactsRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiScopedRagStreamRoute: typeof ApiScopedRagStreamRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/password': {
      id: '/profile/password'
      path: '/password'
      fullPath: '/profile/password'
      preLoaderRoute: typeof ProfilePasswordRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/invites': {
      id: '/profile/invites'
      path: '/invites'
      fullPath: '/profile/invites'
      preLoaderRoute: typeof ProfileInvitesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/api/scoped-rag-stream': {
      id: '/api/scoped-rag-stream'
      path: '/api/scoped-rag-stream'
      fullPath: '/api/scoped-rag-stream'
      preLoaderRoute: typeof ApiScopedRagStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-events': {
      id: '/api/chat-events'
      path: '/api/chat-events'
      fullPath: '/api/chat-events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileRouteChildren {
  ProfileInvitesRoute: typeof ProfileInvitesRoute
  ProfilePasswordRoute: typeof ProfilePasswordRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileInvitesRoute: ProfileInvitesRoute,
  ProfilePasswordRoute: ProfilePasswordRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiArtifactsRoute: ApiArtifactsRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiScopedRagStreamRoute: ApiScopedRagStreamRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
